-- ============================================================
-- verify.sql — Data generation verification for bigbasket_capstone.db
-- Run against: bigbasket_capstone.db (generated by generate_data.py, seed=42)
--
-- VERIFIED RESULTS (confirmed by actually running these queries):
--   products         -> 31
--   customers        -> 50
--   orders           -> 500
--   category_targets -> 6
--
--   orders.status breakdown:
--     Delivered  -> 434
--     Cancelled  -> 42
--     Pending    -> 24
--   (434 + 42 + 24 = 500, matches total order count)
-- ============================================================

SELECT COUNT(*) AS total_products FROM products;
-- Result: 31

SELECT COUNT(*) AS total_customers FROM customers;
-- Result: 50

SELECT COUNT(*) AS total_orders FROM orders;
-- Result: 500

SELECT COUNT(*) AS total_category_targets FROM category_targets;
-- Result: 6

SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status;
-- Result:
-- Cancelled | 42
-- Delivered | 434
-- Pending   | 24
